# Generated by Django 5.1.3 on 2024-11-15 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='compte',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='compte',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='compte',
            name='type_compte',
            field=models.CharField(choices=[('sol', 'Sol'), ('placement', 'Placement'), ('mutuelle', 'Mutuelle')], max_length=10),
        ),
        migrations.CreateModel(
            name='Mutuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_contribution', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_adhesion', models.DateField()),
                ('compte', models.OneToOneField(limit_choices_to={'type_compte': 'mutuelle'}, on_delete=django.db.models.deletion.CASCADE, to='clients.compte')),
            ],
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taux_interet', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('compte', models.OneToOneField(limit_choices_to={'type_compte': 'placement'}, on_delete=django.db.models.deletion.CASCADE, to='clients.compte')),
            ],
        ),
        migrations.CreateModel(
            name='Sol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_sol', models.CharField(max_length=50)),
                ('compte', models.OneToOneField(limit_choices_to={'type_compte': 'sol'}, on_delete=django.db.models.deletion.CASCADE, to='clients.compte')),
            ],
        ),
    ]
